"use server"

import { createServerSupabaseClient } from "@/lib/supabase/server"
import { revalidatePath } from "next/cache"
import { cookies } from "next/headers"
import { redirect } from "next/navigation"

// Helper function to get the current user ID
async function getCurrentUserId(): Promise<string> {
  const supabase = createServerSupabaseClient()

  // Try to get user from session first
  const {
    data: { session },
  } = await supabase.auth.getSession()

  if (session?.user?.id) {
    return session.user.id
  }

  // Fallback to cookie
  const cookieStore = cookies()
  const userId = cookieStore.get("user_id")?.value

  if (!userId) {
    // If no user ID is found, redirect to login
    redirect("/login?redirect=" + encodeURIComponent("/dashboard"))
  }

  return userId
}

export async function saveCoverLetterAction({
  jobId,
  name,
  content,
}: {
  jobId: string
  name: string
  content: string
}): Promise<{ success: boolean; coverLetterId?: string; error?: string }> {
  try {
    const supabase = createServerSupabaseClient()
    const userId = await getCurrentUserId()

    // Get the job to verify it exists and belongs to the user
    const { data: job, error: jobError } = await supabase
      .from("jobs")
      .select("*")
      .eq("id", jobId)
      .eq("user_id", userId)
      .single()

    if (jobError || !job) {
      return { success: false, error: "Job not found or access denied" }
    }

    // Insert the cover letter
    const { data, error } = await supabase
      .from("cover_letters")
      .insert({
        user_id: userId,
        job_id: jobId,
        name,
        content,
        is_ai_generated: true, // Set this to true since it's generated by AI
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select()
      .single()

    if (error) {
      console.error("Error saving cover letter:", error)
      return { success: false, error: "Failed to save cover letter" }
    }

    // Revalidate the job page to show the new cover letter
    revalidatePath(`/jobs/${jobId}`)
    revalidatePath(`/dashboard/cover-letters`)

    return { success: true, coverLetterId: data.id }
  } catch (error) {
    console.error("Error saving cover letter:", error)
    return {
      success: false,
      error: `Failed to save cover letter: ${error instanceof Error ? error.message : String(error)}`,
    }
  }
}
