export const mockJobs = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$120,000 - $150,000",
    description:
      "We are looking for a senior frontend developer to join our team and help build amazing user experiences with React and TypeScript.",
    tags: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    postedAt: "2 days ago",
  },
  {
    id: "2",
    title: "Product Manager",
    company: "StartupXYZ",
    location: "New York, NY",
    type: "Full-time",
    salary: "$100,000 - $130,000",
    description: "Join our product team to drive the vision and strategy for our innovative SaaS platform.",
    tags: ["Product Strategy", "Agile", "Analytics", "Leadership"],
    postedAt: "1 day ago",
  },
  {
    id: "3",
    title: "UX Designer",
    company: "Design Studio",
    location: "Remote",
    type: "Contract",
    salary: "$80 - $100/hour",
    description: "Create beautiful and intuitive user experiences for our clients across various industries.",
    tags: ["Figma", "User Research", "Prototyping", "Design Systems"],
    postedAt: "3 days ago",
  },
  {
    id: "4",
    title: "Backend Engineer",
    company: "CloudTech",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$110,000 - $140,000",
    description: "Build scalable backend systems and APIs using Node.js and cloud technologies.",
    tags: ["Node.js", "AWS", "PostgreSQL", "Docker"],
    postedAt: "1 week ago",
  },
  {
    id: "5",
    title: "Data Scientist",
    company: "AI Innovations",
    location: "Boston, MA",
    type: "Full-time",
    salary: "$130,000 - $160,000",
    description: "Apply machine learning and statistical analysis to solve complex business problems.",
    tags: ["Python", "Machine Learning", "SQL", "TensorFlow"],
    postedAt: "5 days ago",
  },
  {
    id: "6",
    title: "DevOps Engineer",
    company: "Infrastructure Co.",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$115,000 - $145,000",
    description: "Manage and optimize our cloud infrastructure and deployment pipelines.",
    tags: ["Kubernetes", "AWS", "Terraform", "CI/CD"],
    postedAt: "4 days ago",
  },
]
